import Blogs from "@/components/blog/Blogs";
import CategoryContainer from "@/components/category/CategoryContainer";
import Navbar from "@/components/navbar/Navbar";
import SideBlogs from "@/components/sideBlogs/SideBlogs";
export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function Home() {

  return (
    <>
      <Navbar />
      <main className="max-w-[1160px] mx-auto max-xl:px-9">
        <CategoryContainer />
        <div className="flex justify-between max-md:flex-col">
          <Blogs />
          <SideBlogs />
        </div>
      </main>
      {/* <Footer /> */}
    </>
  );
}
